#image: docker:stable
#image: arm64v8/alpine
#image: docker:18-git
image: arm64v8/docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build

21.11-bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:21.11-bullseye --no-cache --rm -f dists/21.11-bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:21.11-bullseye
#  only:
#  - 21.11-bullseye@mjames/ktd-arm64

22.05-bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:22.05-bullseye --no-cache --rm -f dists/22.05-bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:22.05-bullseye
#  only:
#  - 22.05-bullseye@mjames/ktd-arm64

22.11-bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:22.11-bullseye --no-cache --rm -f dists/22.11-bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:22.11-bullseye
#  only:
#  - 22.11-bullseye@mjames/ktd-arm64

master-bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:master-bullseye --no-cache --rm -f dists/master-bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:master-bullseye
#  only:
#  - master-bullseye@mjames/ktd-arm64