#image: docker:stable
#image: arm64v8/alpine
#image: docker:18-git
image: arm64v8/docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build


master-bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:master-bullseye --no-cache --rm -f dists/master-bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:master-bullseye
#  only:
#  - master-bullseye@mjames/ktd-arm64
