image: docker:stable
#image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build


buster-full-armhf:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:master-buster --no-cache --rm -f dists/buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:master-buster
  - docker image rm kohaaloha/arm64:koha-testing:master-buster

#  only:
#- master-ka-full@mjames/koha-testing-docker


