#image: docker:stable
#image: arm64v8/alpine
#image: docker:18-git
image: arm64v8/docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build

#22.05-bookworm:
#  stage: build
#  script:
#  - docker build -t kohaaloha/arm64:22.05-bookworm --no-cache --rm -f dists/bookworm/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push kohaaloha/arm64:22.05-bookworm
#    #  - docker image rm kohaaloha/arm64:koha-testing:master-bullseye
#   #only:
#    #- master-bullseye@mjames/ktd-arm64
#
22.05-bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:22.05-bullseye --no-cache --rm -f dists/bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:22.05-bullseye
    #  - docker image rm kohaaloha/arm64:koha-testing:master-bullseye
   #only:
    #- master-bullseye@mjames/ktd-arm64

#22.05-buster:
#  stage: build
#  script:
#  - docker build -t kohaaloha/arm64:22.05-buster --no-cache --rm -f dists/buster/Dockerfile .
#  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#  - docker push kohaaloha/arm64:22.05-buster
#    #  - docker image rm kohaaloha/arm64:koha-testing:master-bullseye
#   #only:
#    #- master-bullseye@mjames/ktd-arm64
#

