#image: docker:stable
#image: arm64v8/alpine
#image: docker:18-git
image: arm64v8/docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
    # See https://github.com/docker-library/docker/pull/166
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build

22.05-bookworm:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:22.05-bookworm --no-cache --rm -f dists/22.05-bookworm/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:22.05-bookworm
#  only:
#  - 22.05-bookworm@mjames/ktd-arm64

22.05-bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:22.05-bullseye --no-cache --rm -f dists/22.05-bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:22.05-bullseye
#  only:
#  - 22.05-bullseye@mjames/ktd-arm64

22.05-buster:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:22.05-buster --no-cache --rm -f dists/22.05-buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:22.05-buster
#  only:
#  - 22.05-buster@mjames/ktd-arm64

22.05-jammy:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:22.05-jammy --no-cache --rm -f dists/22.05-jammy/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:22.05-jammy
#  only:
#  - 22.05-jammy@mjames/ktd-arm64

22.05-sid:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:22.05-sid --no-cache --rm -f dists/22.05-sid/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:22.05-sid
#  only:
#  - 22.05-sid@mjames/ktd-arm64

master-bookworm:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:master-bookworm --no-cache --rm -f dists/master-bookworm/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:master-bookworm
#  only:
#  - master-bookworm@mjames/ktd-arm64

master-bullseye:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:master-bullseye --no-cache --rm -f dists/master-bullseye/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:master-bullseye
#  only:
#  - master-bullseye@mjames/ktd-arm64

master-buster:
  stage: build
  script:
  - docker build -t kohaaloha/arm64:master-buster --no-cache --rm -f dists/master-buster/Dockerfile .
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker push kohaaloha/arm64:master-buster
#  only:
#  - master-buster@mjames/ktd-arm64